# pip install pre-commit
# pre-commit install
# As default runs only on commited files
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-merge-conflict
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
    - id: reorder-python-imports
      args: [--py3-plus]
      exclude: cat_file/filetypes/__init__.py
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--safe, -l 120]
      language_version: python3.8
